//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc8amAvengersTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public int EmpSalary { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual Employee Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
